### ISSUE TITLE
Enforce formatting style?

### ISSUE THREAD

**Issue by mesca** [pyRiemann/pyRiemann#102]
Formatting style across the project is inconsistent.
I would suggest to fix this issue by using [Black](https://github.com/psf/black). It works pretty well, and it is very easy to use.

**Comment by agramfort** [comment]
I am a bit reluctant to do such a massive reformatting of a code. It breaks
PRs and you loose
the origin of the code (git blame harder).

I think there are more urgent things to do. Migrate to GH actions, add
flake8 to CI, move from nose to pytest etc.

>
