### ISSUE TITLE
Incorrect cospectrum

### ISSUE THREAD

**Issue by qbarthelemy** [pyRiemann/pyRiemann#116]
**Problems**

Function `cospectrum` had been modified here https://github.com/pyRiemann/pyRiemann/commit/9a6dbeef03f61c7658c8902923d0f22d84b57c1c#diff-b256f1ac840adebcb1b8bd17d18f050b62b1b6b7f9ef86331083bfbccd0d16d6
but the output is defined as the squared modulus of the cross-spectra, instead of the real part, as mentionned in #90.

Moreover, `cospectrum(x, fmin=20)` raises the `TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'`
at line https://github.com/pyRiemann/pyRiemann/commit/9a6dbeef03f61c7658c8902923d0f22d84b57c1c#diff-b256f1ac840adebcb1b8bd17d18f050b62b1b6b7f9ef86331083bfbccd0d16d6R136 : `f = numpy.arange(0, 1, 1.0 / number_freqs) * (fs / 2.0)`, because `fs` is None.

**Cross-spectra and co-spectra**

![Issue_CoSpectrum](https://user-images.githubusercontent.com/5346669/119399642-6d250580-bcd9-11eb-906f-8cf46312dc56.png)

**Solution**

PR in progress...

**Comment by alexandrebarachant** [comment]
this is intended to be the squared modulus (cross-spectrum). it could be great to have the option to choose what you want if you make a PR.

**Comment by qbarthelemy** [comment]
If the output of the function is the (squared) modulus, the phase is definitively lost.

It is better to return the raw complex cross-spectrum, and then users can compute the feature they need: real part (for co-spectrum), imaginary part, modulus (useful for coherence) or phase.

**Comment by alexandrebarachant** [comment]
yeah, phase is lost. its intented to be a "unnormalized" version of the coherence (i.e. what covariance is to correlation). I would say the best option is to add a parameter that allows you to switch between the different version (you could even throw in normalization to have coherence estimation). This way it won't break existing pipeline that expect non-complex outputs.

**Comment by qbarthelemy** [comment]
Closed by #118.
