### ISSUE TITLE
TypeError: fit() missing 1 required positional argument: 'y'

### ISSUE THREAD

**Issue by moonj94** [pyRiemann/pyRiemann#130]
I want to run XDawnCovariances and TangentSpace without providing a 'y' variable, which is seemingly possible given the documentation/function help. but for some reason I am getting the error:

`TypeError: fit() missing 1 required positional argument: 'y'`

Can anyone help me with this? I guess what I'm trying to go for is an unsupervised determination of Xdawn and TangentSpace.

Thanks!

**Comment by agramfort** [comment]
xdawn does require targets:

https://github.com/pyRiemann/pyRiemann/blob/master/pyriemann/spatialfilters.py#L77

>

**Comment by sylvchev** [comment]
@moonj94 
XDAWN is a supervised filter, you need the y. Could we close this issue or have you any other question?
