### ISSUE TITLE
Matplotlib dependency

### ISSUE THREAD

**Issue by sylvchev** [pyRiemann/pyRiemann#134]
There is a direct matplotlib dependency in pyriemann/stats.py:4

This dependency is implicit in [requirements.txt](https://github.com/pyRiemann/pyRiemann/blob/master/requirements.txt#L6) as seaborn is indicated, but [setup.py](https://github.com/pyRiemann/pyRiemann/blob/master/setup.py#L36) do not mention this.

This cause pytest to fail on a clean install.

**Comment by agramfort** [comment]
we should nest the import of matplotlib to make sure it's optional

>
