### ISSUE TITLE
Logo for pyRiemann

### ISSUE THREAD

**Issue by plcrodrigues** [pyRiemann/pyRiemann#137]
Hi, everyone.

I would like to propose that we think of a logo for our dearest package ! :)

I have no training whatsoever in design and/or logo creation, so I must say that I don't have any strong opinion of what we should or should not include in a logo. With that said, I have a first suggestion and would like to know what you guys think. 

<img src="https://user-images.githubusercontent.com/4588557/131631158-5a71af1e-3068-4518-ac70-511923e3e41e.png" width="20%">

We could also include colors, such as in the two proposals here below.

<img src="https://user-images.githubusercontent.com/4588557/131632233-fb13aa3e-48da-4128-9d5d-e2f8afc884b7.png" width="20%">
<img src="https://user-images.githubusercontent.com/4588557/131632621-cd42eb19-f100-49dd-b359-ded11a141795.png" width="20%">

Well, that's it. I would be happy to know whether:
1) The logo itself seems OK or if we should go onto something else
2) What you think of the colors? We can of course play with other combinations (with the help of https://coolors.co/)

Cheers,
Pedro

**Comment by agramfort** [comment]
I like the yellow one better :)

>

**Comment by qbarthelemy** [comment]
Blue and orange is fine for me!
A regret: with respect the Fig 1.2 of your thesis, time-series are lost, although they are input data of pyRiemann. What about adding 2 or 3 waves? 

A quick try:
![pR2](https://user-images.githubusercontent.com/5346669/131733940-1e9d5c75-e542-480b-84fc-bc10eb7943bd.png)

**Comment by lkorczowski** [comment]
In like the white one better BUT it doesn't render well in dark mode due to transparency. 
<img width="198" alt="Screenshot 2021-09-01 at 23 06 53" src="https://user-images.githubusercontent.com/15196605/131745342-9bde10a5-4323-4008-9183-b461297bd069.png">

For the colored one, I don't have a strong opinion. Maybe the blue one because I did `np.random.randint(2)` and it gave me 0 (twice), so the first one seems appropriate.

**Comment by plcrodrigues** [comment]
I like very much the suggestion by @qbarthelemy to add some signals. 

![logo-pyRiemann-base svg](https://user-images.githubusercontent.com/4588557/131802728-6bca0e08-9229-4800-ac98-51e384fa5adb.png)

Here you go for a second iteration. What do you guys think ?

I am very much divided between the two color palettes. The yellow one has more "punch" into it whereas the blue one looks more "pythonic" to me.

**Comment by sylvchev** [comment]
So nice with the time series. I agree with your interpretation Pedro, blue is pythonic, yellow is punchy

**Comment by agramfort** [comment]
blue and orange is much letter contrasted to me. Yellow is my preferred one.

**Comment by lkorczowski** [comment]
Very nice with signals.

**Comment by alexandrebarachant** [comment]
great job, i like them.  the blue/orange and the yellow one are really great, and i have a slight preference for the blue one.

**Comment by qbarthelemy** [comment]
What about this one?

![pR3](https://user-images.githubusercontent.com/5346669/131886452-f074f852-a575-44e0-9206-34d37ddbbdff.png)

**Comment by agramfort** [comment]
black on dark blue is not contrasted enough

my 2c

>

**Comment by qbarthelemy** [comment]
![pR3](https://user-images.githubusercontent.com/5346669/131889381-be2f36e9-af14-4999-9123-0de85b89b034.png)

**Comment by plcrodrigues** [comment]
<img src="https://user-images.githubusercontent.com/4588557/131890469-cb8ee30e-6034-4a83-8894-d366e87d0da4.png" width="60%">

**Comment by plcrodrigues** [comment]
@agramfort : I would say it's quite contrasted now, no ? (and it remains quite pythonic)

**Comment by agramfort** [comment]
yes much better 👌👌👌

>

**Comment by plcrodrigues** [comment]
Cool, looks like we have a winner. I will leave this issue open for a few days just in case someone drops in with new suggestions.

**Comment by sylvchev** [comment]
Brilliant! Winner for me also!

**Comment by qbarthelemy** [comment]
@agramfort , I believe that your are the only one who can update the logo of the repo.

**Comment by agramfort** [comment]
I think it's done

**Comment by qbarthelemy** [comment]
I think that we can close this issue.
