### ISSUE TITLE
Wrong documentation in Riemannian distance function

### ISSUE THREAD

**Issue by gzoumpourlis** [pyRiemann/pyRiemann#148]
Hi,

It seems that there is a mistake in the documentation of the function pyriemann.utils.distance.distance_riemann
https://github.com/pyRiemann/pyRiemann/blob/f06a33ebfe37e8bb8a28f0b3178ce7d9974c70d7/pyriemann/utils/distance.py#L67

According to the code comments, the power applied to the sum, is **-**1/2, while it should be **+**1/2.
I.e., it should be `d = {\left( \sum_i \log(\lambda_i)^2 \right)}^{1/2}`.

Reference:
"Positive Definite Matrices", Rajendra Bhatia, page 217, Equation 6.14.
http://www.cmat.edu.uy/~lessa/tesis/Positive%20Definite%20Matrices.pdf

**Comment by qbarthelemy** [comment]
Thanks, good catch!

This mistake will be corrected when commit 3e7afc9 will be merged in #147.
