### ISSUE TITLE
Issues with testing the classifier with testing dataset

### ISSUE THREAD

**Issue by ibr2011** [pyRiemann/pyRiemann#152]
Hi, 

I followed the steps of classifying the training dataset using Minimum distance to mean, Tangent Space Logistic Regression, and CSP + logistic regression. However, I get errors when I want to test the model with the testing dataset(i.e. using the function score or predict)

Errors displayed are:
`'MDM' object has no attribute 'covmeans_'`
`'TSclassifier' object has no attribute '_pipe'`
`'CSP' object has no attribute 'filters_'`

Can someone help me with this?

Regards

**Comment by ibr2011** [comment]
A snippet of my code is below: 

```
epochs_data_train = 1e6 * users_training_validation.get_data()
y_train= users_training_validation.events[:, -1]
epochs_data_test = 1e6 * users_testing.get_data()
y_test = users_testing.events[:, -1]

# compute covariance matrices
cov_data_train = Covariances(estimator="oas").transform(epochs_data_train)
cov_data_test = Covariances(estimator="oas").transform(epochs_data_test)

cv = KFold(n_splits=10, shuffle=True, random_state=42)

clf_mdm = MDM(metric=dict(mean='riemann', distance='riemann'))

# Use scikit-learn Pipeline with cross_val_score function
scores = cross_val_score(clf_mdm, cov_data_train, y_train, cv=cv, n_jobs=1)

# Printing the results
class_balance = np.mean(y_train == y_train[0])
class_balance = max(class_balance, 1. - class_balance)
print("MDM Classification accuracy: %f / Chance level: %f" % (np.mean(scores),
                                                              class_balance))

# Test with Minimum distance to mean
clf_mdm.score(cov_data_test, y_test)
```

**Comment by ibr2011** [comment]
I didn't fit the classifier

**Comment by sylvchev** [comment]
Hi @ibr2011 
Thanks for taking the time to report your issue, even if you could solve it by yourself. Do not hesitate to open new issue if you get errors.
