### ISSUE TITLE
release 0.2.8

### ISSUE THREAD

**Issue by agramfort** [pyRiemann/pyRiemann#176]
@alexandrebarachant @qbarthelemy @plcrodrigues @sylvchev ok to release 0.2.8? anything you would like to add/fix before?

**Comment by plcrodrigues** [comment]
LGTM

**Comment by sylvchev** [comment]
@emmanuelkalunga worked on a nice example for transfer learning for our PR #155 (on another branch to make it tidy, [visible here](https://github.com/emmanuelkalunga/pyRiemann/tree/feature/example)), I think we could finish this within 2 days.

**Comment by agramfort** [comment]
can you open a PR for this? then I'll cut a release after this one is merged

**Comment by sylvchev** [comment]
@agramfort I see that #168 is ready to merge, the green button is yours.
I'm working on #155 to finshing wrapping up the PR.

**Comment by qbarthelemy** [comment]
Indeed, https://github.com/pyRiemann/pyRiemann/pull/172 should be merged, because it changes the behavior of `mean_power`.

**Comment by qbarthelemy** [comment]
AFK for three weeks, I let you release 0.2.8 ! Thx!

**Comment by agramfort** [comment]
done
https://twitter.com/agramfort/status/1548668079961522178?s=20&t=iGqtyFQjYfe7Igm1IpZmJA

and it's now 0.3 as it's more than a minor update !

**Comment by sylvchev** [comment]
Thanks @agramfort !
