### ISSUE TITLE
Allow processing of HPD matrices

### ISSUE THREAD

**Issue by qbarthelemy** [pyRiemann/pyRiemann#204]
## Description

A [Hermitian positive definite (HPD) matrix](https://en.wikipedia.org/wiki/Definite_matrix#Definitions_for_complex_matrices) $M$ is defined as:
$M = A + iB$
where $A$ is a symmetric positive definite (SPD) matrix and $B$ is a skew-symmetric matrix.

pyRiemann should be adapted to process such complex-valued data.

## [1](#1) - Tests

To validate modifications and to complete test, we must also add a new function to generate generic, SPD or HPD matrices.
- [x] `make_matrices(n_matrices, n_channels, kind='spd' | 'hpd', same_eigvecs=True)` will be able to generate SPD or HPD matrices;
- [x] `get_covmats` will be replaced by `get_matrices`.

Then, tests will be:
```
@pytest.mark.parametrize("kind", ['spd', 'hpd'])
def test_distance_harmonic(get_matrices, kind):
    n_matrices, n_channels = 6, 5
    mats = get_matrices(n_matrices, n_channels, kind=kind)
```

## [2](#2) - Utils

The first obvious change is to update matrix operators,
`pyriemann.utils.base._matrix_operator`, adding `.conj()`:
`D = (eigvecs * eigvals) @ np.swapaxes(eigvecs.conj(), -2, -1)`

Other functions which must be adapted too:
- [x] base operators,
- [x] distances,
- [x] geodesics,
- [x] tangent space,
- [x] means,
- [x] medians,
- [x] ajd,
- [ ] kernels (?).

## [3](#3) - Covariance matrices

For [complex inputs](https://en.wikipedia.org/wiki/Covariance_matrix#Complex_random_vectors), like in [radar image processing](https://ammarmian.github.io/pdf/wiley_book_2021.pdf), covariance matrix estimations must use a Hermitian self-multiplication.

For the sample covariance matrix (scm), pseudo-covariance $C = \frac{1}{n} X X^T$ must be replaced by actual covariance $C = \frac{1}{n} X X^H$.

This is OK for `cov` estimator realying on [np.cov](https://numpy.org/doc/stable/reference/generated/numpy.cov.html).
But, most of covariance estimators rely on [scikit-learn](https://scikit-learn.org/stable/modules/covariance.html), processing only real inputs: 
- [x] `scm`,
- [x] `lwf`,
- [x] `mcd`,
- [x] `oas`,
- [x] and `Shrinkage` based on `shrunk_covariance`.

We must ensure that estimators coded into pyRiemann process complex inputs: 
- [x] `sch`.

## [4](#4) - Cross-spectral matrices

Cross-spectral matrices are HPD matrices, where real parts are co-spectral matrices and imaginary parts are quadrature spectra capturing phase information.

Providing richer features, some works have shown the interest of classifying HPD matrices rather than SPD ones.
[2017 - Dehgan - Classification in Riemannian space An application to sleep EEG.pdf](https://github.com/pyRiemann/pyRiemann/files/9791961/2017.-.Dehgan.-.Classification.in.Riemannian.space.An.application.to.sleep.EEG.pdf)
[2019 - Xu - Feature extraction from the Hermitian manifold for Brain-Computer Interfaces.pdf](https://github.com/pyRiemann/pyRiemann/files/9791963/2019.-.Xu.-.Feature.extraction.from.the.Hermitian.manifold.for.Brain-Computer.Interfaces.pdf)

- [x] Add class `CrossSpectra`.

#### Example

```
"""HPD matrices classification by MDM"""

import numpy as np
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.model_selection import cross_val_score, KFold

from pyriemann.classification import MDM
from pyriemann.utils.covariance import cross_spectrum


###############################################################################


class CrossSpectra(BaseEstimator, TransformerMixin):
    """Estimation of cross-spectral matrices.

    Complex cross-spectral matrices are HPD matrices estimated as the spectrum
    covariance in the frequency domain. It returns a 4-d array with a
    cross-spectral matrix for each input and in each frequency bin of the
    Fourier transform.

    Parameters
    ----------
    window : int, default=128
        The length of the FFT window used for spectral estimation.
    overlap : float, default=0.75
        The percentage of overlap between window.
    fmin : float | None, default=None
        The minimal frequency to be returned.
    fmax : float | None, default=None
        The maximal frequency to be returned.
    fs : float | None, default=None
        The sampling frequency of the signal.

    Attributes
    ----------
    freqs_ : ndarray, shape (n_freqs,)
        If transformed, the frequencies associated to cospectra.
        None if ``fs`` is None.

    See Also
    --------
    Covariances
    Coherences

    References
    ----------
    .. [1] https://en.wikipedia.org/wiki/Cross-spectrum
    """

    def __init__(self, window=128, overlap=0.75, fmin=None, fmax=None,
                 fs=None):
        """Init."""
        self.window = _nextpow2(window)
        self.overlap = overlap
        self.fmin = fmin
        self.fmax = fmax
        self.fs = fs

    def fit(self, X, y=None):
        """Fit.

        Do nothing. For compatibility purpose.

        Parameters
        ----------
        X : ndarray, shape (n_matrices, n_channels, n_times)
            Multi-channel time-series.
        y : None
            Not used, here for compatibility with sklearn API.

        Returns
        -------
        self : CrossSpectra instance
            The CrossSpectra instance.
        """
        return self

    def transform(self, X):
        """Estimate cross-spectral matrices.

        Parameters
        ----------
        X : ndarray, shape (n_matrices, n_channels, n_times)
            Multi-channel time-series.

        Returns
        -------
        X_new : ndarray, shape (n_matrices, n_channels, n_channels, n_freqs)
            Cross-spectral matrices for each input and for each frequency bin.
        """
        X_new = []

        for i in range(len(X)):
            S, freqs = cross_spectrum(
                X[i],
                window=self.window,
                overlap=self.overlap,
                fmin=self.fmin,
                fmax=self.fmax,
                fs=self.fs)
            X_new.append(S)
        self.freqs_ = freqs

        return np.array(X_new)


###############################################################################
# MDM on HPD matrices

n_matrices, n_channels, n_times = 50, 4, 5000
data_eeg = np.random.randn(2 * n_matrices, n_channels, n_times)

CrossSp = CrossSpectra(window=128, overlap=0.5, fmin=1, fmax=32, fs=128)
data_spec = CrossSp.transform(data_eeg)

ftarget = 10
X = np.squeeze(data_spec[..., CrossSp.freqs_ == ftarget])
y = [0] * n_matrices + [1] * n_matrices


mdm = MDM(metric='riemann')
cv = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(mdm, X, y, cv=cv, n_jobs=1)
```

#### API change

- [x] Class `CospCovariances` could be renamed `CoSpectra` and simply coded as:

```
class CoSpectra(CrossSpectra):
    """Estimation of co-spectral matrices.

    Co-spectral matrices are SPD matrices estimated as the real part of the
    spectrum covariance in the frequency domain. It returns a 4-d array with a
    o-spectral matrix for each input and in each frequency bin of the
    Fourier transform.

    Parameters
    ----------
    window : int, default=128
        The length of the FFT window used for spectral estimation.
    overlap : float, default=0.75
        The percentage of overlap between window.
    fmin : float | None, default=None
        The minimal frequency to be returned.
    fmax : float | None, default=None
        The maximal frequency to be returned.
    fs : float | None, default=None
        The sampling frequency of the signal.

    Attributes
    ----------
    freqs_ : ndarray, shape (n_freqs,)
        If transformed, the frequencies associated to cospectra.
        None if ``fs`` is None.

    See Also
    --------
    Covariances
    CrossSpectra
    """

    def transform(self, X):
        """Estimate co-spectral matrices.

        Parameters
        ----------
        X : ndarray, shape (n_matrices, n_channels, n_times)
            Multi-channel time-series.

        Returns
        -------
        X_new : ndarray, shape (n_matrices, n_channels, n_channels, n_freqs)
            Co-spectral matrices for each input and for each frequency bin.
        """
        X_new = super().transform(X)
        return X_new.real
```

**Comment by agramfort** [comment]
sounds like an easy and valuable improvement 👍

**Comment by plcrodrigues** [comment]
Yeah, sounds like a nice plan. It would just be important to adapt the Riemannian Gaussian functions, because their sampling in SPD or HPD manifold are different. Go for it @qbarthelemy !

**Comment by qbarthelemy** [comment]
For covariance matrices computed on complex-valued inputs, see https://github.com/pyRiemann/pyRiemann/issues/204#2,
unfortunately, we must plan to re-implement covariance estimators imported from scikit-learn: `scm`, `lwf`, `mcd`, and `oas`.
See https://github.com/scikit-learn/scikit-learn/issues/25519

**Comment by gabelstein** [comment]
[This paper (section 3)](https://doi.org/10.1109/ICASSP.2007.366399) describes a way for using generic estimators for complex valued covariance estimation. 
I will figure out how to implement this. Probably only needs small changes in the covariances function.

**Comment by qbarthelemy** [comment]
Kernels for HPD matrices will be done later.
