### ISSUE TITLE
equations broken in the doc

### ISSUE THREAD

**Issue by agramfort** [pyRiemann/pyRiemann#207]
equations eg at https://pyriemann.readthedocs.io/en/latest/generated/pyriemann.utils.tangentspace.log_map_logeuclid.html#pyriemann.utils.tangentspace.log_map_logeuclid are broken

**Comment by qbarthelemy** [comment]
All equations are broken.

**Comment by agramfort** [comment]
can you replicate locally?

**Comment by qbarthelemy** [comment]
No, but my environnent is a little old: my sphinx version is 4.5.0, instead of 5.3.0.
