### ISSUE TITLE
No module named 'pyriemann.transfer'

### ISSUE THREAD

**Issue by hubert3102** [pyRiemann/pyRiemann#212]
I have updated my pyriemann version to 0.3. However, I still can't run the following code. The error always showed up with 'No module named 'pyriemann.transfer' .
What should I do to cope with this problem? 

``
from pyriemann.transfer import (
    encode_domains,
    TLDummy,
    TLCenter,
    TLClassifier,
    TLSplitter,
)
``

**Comment by qbarthelemy** [comment]
Transfer learning has been added in version 0.3.1.dev

**Comment by agramfort** [comment]
try

pip install git+https://github.com/pyRiemann/pyRiemann

**Comment by qbarthelemy** [comment]
@hubert3102, can you close the issue if it is ok for you?
