### ISSUE TITLE
Speed up pairwise_distance

### ISSUE THREAD

**Issue by agramfort** [pyRiemann/pyRiemann#224]
currently the pairwise_distance function does a double for loop to compute all distances. It makes the computation quadratic on all levels. I should be possible to avoid this. Eg certain metrics are symmetric so we can divided by 2 and maybe for the others we can avoid computing more than once the eigenvecs/values of each matrix.

a fun challenge @qbarthelemy :)

**Comment by qbarthelemy** [comment]
When Y is None, only half of the pairwise distance matrix is computed, like [scipy.pdist](https://github.com/scipy/scipy/blob/v1.10.0/scipy/spatial/distance.py#L2592):
https://github.com/pyRiemann/pyRiemann/blob/master/pyriemann/utils/distance.py#L331
Remark that it is false for non-symmetric divergences.

Storing all EVDs, and then computing pairwise distances seems a good idea to speed up pairwise AIR distances.
But I do not see how to generalize to any kind of distance.

SciPy uses a double for-loop for [scipy.cdist](https://github.com/scipy/scipy/blob/v1.10.0/scipy/spatial/distance.py#L2598).

**Comment by qbarthelemy** [comment]
When Y is None, only half of the pairwise distance matrix is computed, like [scipy.pdist](https://github.com/scipy/scipy/blob/v1.10.0/scipy/spatial/distance.py#L2592):
https://github.com/pyRiemann/pyRiemann/blob/master/pyriemann/utils/distance.py#L331
Remark that it is false for non-symmetric divergences.

Storing all EVDs, and then computing pairwise distances seems a good idea to speed up pairwise AIR distances.
But I do not see how to generalize to any kind of distance.

SciPy uses a double for-loop for [scipy.cdist](https://github.com/scipy/scipy/blob/v1.10.0/scipy/spatial/distance.py#L2598).

**Comment by agramfort** [comment]
I think we can definitely do better

<img width="797" alt="Screenshot 2023-02-18 at 16 05 16" src="https://user-images.githubusercontent.com/161052/219876170-b04fd22b-e04c-4341-8e3f-01297b89643a.png">

**Comment by agramfort** [comment]
I am afraid so to some extent

**Comment by gabelstein** [comment]
I wrote the pairwise functions for euclid, harmonic, logeuclid and riemann. 
The rest does not seem as easy to do as these four. Should we just go with these four for the time being? I would strongly propose so as the speedup is immense and the other metrics are probably not heavily used.
Maybe someone else will do the rest some day.

All but the riemann distance use the sklearn pairwise_distance and just transform the input matrices beforehand.

euclid
1.11 ms ± 395 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
165 ms ± 8.28 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
harmonic
2.32 ms ± 818 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
1.45 s ± 532 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
logeuclid
5.13 ms ± 273 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
2.14 s ± 475 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
riemann
229 ms ± 7.26 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.97 s ± 762 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

**Comment by agramfort** [comment]
Yes let's do one thing at a time. Can you open the PR? Thx
