### ISSUE TITLE
Package is also on conda-forge

### ISSUE THREAD

**Issue by hoechenberger** [pyRiemann/pyRiemann#226]
Hello, @larsoner and I packaged pyRiemann for conda-forge: https://anaconda.org/conda-forge/pyriemann

If you're interested, the install docs should be updated.

Please LMK what you think!

Richard

**Comment by qbarthelemy** [comment]
Yes, it is a good improvement!
Can you open a PR to add a section `Using Conda` in `readme.md` and `doc/installing.rst`?

**Comment by sylvchev** [comment]
Yes, this is a very nice initiative and it should be advertised!

**Comment by hoechenberger** [comment]
Yes i can do that 

Please do feel free to ping me should you not hear back from me within a week or so!
