### ISSUE TITLE
Significant drop in accuracy for release version 0.4

### ISSUE THREAD

**Issue by DingkunLiu** [pyRiemann/pyRiemann#241]
I tried to run my old code on version 0.4 and observed a significant drop in accuracy, which could be as large as 10 percent. I create a simple example to replicate the bug with my own data. I think the bug is about the `XdawnCovariance` estimation. Could you please investigate this issue? 

The data and code are attached. I compared the result using the same method with release version 0.3 and 0.4.
[sample.zip](https://github.com/pyRiemann/pyRiemann/files/11128415/sample.zip)

**Comment by qbarthelemy** [comment]
Thank you so much @DingkunLiu for this relevant issue!

Regression has been introduced in #214, wrongly removing a reshape step 
https://github.com/pyRiemann/pyRiemann/pull/214/commits/45354b2c2883f6bf4a4855e64fac932a66cc2438#diff-f3762b7e6323643948e27df9777f362069925823b4779fe3571f5e1db3a400e9L104
