### ISSUE TITLE
FIX: var naming convention?

### ISSUE THREAD

**Issue by kingjr** [pyRiemann/pyRiemann#25]
Since there's going to be a bckward incompatibility with the attributes, you may also want to change some of the param names: i.e. underscore to separate words (e.g. `applyfilters` =>`apply_filter`), explicit naming (e.g. `n` => `n_sample`), no uppercase (e.g. `Nx`) etc.

WDYT?

**Comment by alexandrebarachant** [comment]
you are right. 
I will take time to do a code review this week-end, and hunt down this kind of thing.

**Comment by qbarthelemy** [comment]
Decision to replace `n_trials` by `n_matrices` here: https://github.com/pyRiemann/pyRiemann/pull/140#discussion_r714660528

**Comment by qbarthelemy** [comment]
Closed with #173, #174 and #175.
