### ISSUE TITLE
update to readthedocs v2

### ISSUE THREAD

**Issue by agramfort** [pyRiemann/pyRiemann#255]
see https://blog.readthedocs.com/migrate-configuration-v2/

we need to migrate to new system...

**Comment by qbarthelemy** [comment]
By the way, [documentation](https://pyriemann.readthedocs.io/en/latest/) is no longer updated since June 19 (7 commits)

**Comment by agramfort** [comment]
what is your login on https://readthedocs.org/ so I can make you admin
and you can look into this?
