### ISSUE TITLE
Bug in TLStretch?

### ISSUE THREAD

**Issue by apmellot** [pyRiemann/pyRiemann#257]
Hello!
I was going through the new transfer learning estimators and I noticed that in TLStretch the dispersions are computed as the sum of the squared distance to the mean:
https://github.com/pyRiemann/pyRiemann/blob/master/pyriemann/transfer/_estimators.py#L289-L294
Isn't there a 1/N term missing? The way it is defined will not work when there are different numbers of points in the source and target.

**Comment by apmellot** [comment]
I am on it

**Comment by sylvchev** [comment]
Thanks!

**Comment by plcrodrigues** [comment]
Thanks @apmellot ! Good catch.

**Comment by qbarthelemy** [comment]
When all weights are equal to `1 / n`, `arg min S2 / n` and `arg min S2` are the same (`S2` denoting the sum of squares).

**Comment by qbarthelemy** [comment]
Closed by #258
