### ISSUE TITLE
FGDA have oversized parameters

### ISSUE THREAD

**Issue by sylvchev** [pyRiemann/pyRiemann#261]
MOABB store on disk the trained models when conducting benchmarks, using pickle. While all pyriemann based pipelines have models that are between 30-60 Kb when stored on disk, the models based on FGDA (like FgMDM) are 1000x larger (30-60 Mb). 

I found that this is caused by the storage of a [large matrix](https://github.com/pyRiemann/pyRiemann/blob/37bc0d0985efead00bee81322cebfec3249f0370/pyriemann/tangentspace.py#L287) to allow inverse transform of FGDA. The inverse transform is not implemented, there is only a private function [`retro_project()`](https://github.com/pyRiemann/pyRiemann/blob/37bc0d0985efead00bee81322cebfec3249f0370/pyriemann/tangentspace.py#L290C9-L290C23) that is not called anywhere.

I propose to keep this `retro-project()` function, and to move the computation and storage of the big matrix `_W` from `fit` to `retro-project()`. This will keep memory footprint of the model under control and ensure backward compatibility, but it will have a higher computation cost for those who are using this private function.

**Comment by qbarthelemy** [comment]
> there is only a private function retro_project() that is not called anywhere.

Private function `_retro_project` is called into `transform` and `fit_transform`, see
https://github.com/pyRiemann/pyRiemann/blob/37bc0d0985efead00bee81322cebfec3249f0370/pyriemann/tangentspace.py#L330
and
https://github.com/pyRiemann/pyRiemann/blob/37bc0d0985efead00bee81322cebfec3249f0370/pyriemann/tangentspace.py#L351

**Comment by sylvchev** [comment]
Ok, I missed it.
As we are dealing with large matrices, the tangent space dimension is big. I don't see how to reduce the parameters stored in memory.
I'm closing the issue.
