### ISSUE TITLE
Python3.12: tests fail

### ISSUE THREAD

**Issue by penguinpee** [pyRiemann/pyRiemann#262]
Fedora has introduced Python3.12 in rawhide (development) and f39. Building with Python3.12 tests fail. Please see [pyriemann_test_failures.log](https://github.com/pyRiemann/pyRiemann/files/12539216/pyriemann_test_failures.log).

**Comment by qbarthelemy** [comment]
Many errors have been fixed by https://github.com/pyRiemann/pyRiemann/pull/254
Can you force the update of pyRiemann to have the latest version and re-run tests?

**Comment by penguinpee** [comment]
Sure I can try applying the patch. :crossed_fingers: Thanks for the quick response. I'll report back here with the results.

**Comment by penguinpee** [comment]
Updating to 0.5 and applying the patch from #254 has all ducks in a row again. Thanks!
