### ISSUE TITLE
Version 1.2.1 has never been released

### ISSUE THREAD

**Issue by penguinpee** [pyRiemann/pyRiemann#263]
Neither on GitHub nor on PyPI has 1.2.1 officially been released. A tag on GitHub is all that points to version 1.2.1. Please consider releasing 1.2.1 on at least PyPI.

**Comment by qbarthelemy** [comment]
Being at 0.5, version 1.2.1 was never released.
I'm not sure I understand the problem. Can you give more elements?

**Comment by penguinpee** [comment]
My bad! :blush:
This belongs to a different package. Too much build wrangling...
