### ISSUE TITLE
Interactive examples for pyRiemann

### ISSUE THREAD

**Issue by edublancas** [pyRiemann/pyRiemann#266]
Hi pyRiemann team!

My team maintains a few [open-source](https://github.com/ploomber/jupysql) projects, and we've seen that having interactive examples greatly helps newcomers! We're maintaining a Binder cluster that provides ephemeral JupyterLab sessions ([example](https://binder.ploomber.io/v2/gh/ploomber/jupysql/master?urlpath=lab/tree/doc/quick-start.md)). It essentially spins up a JupyterLab session with pre-made examples.

We're happy to sponsor pyRiemann with some computing power. If you're interested, please get in touch with me! (my contact info is in my [profile](https://github.com/edublancas/))

**Comment by agramfort** [comment]
yes it would be cool to have "launch binder" button on our sphinx gallery
examples like sklearn has.

**Comment by edublancas** [comment]
Sounds good! I went ahead and enabled our binder cluster for pyRiemann: https://binder.ploomber.io/v2/gh/pyRiemann/pyRiemann/master?filepath=examples

It's giving some issues because our current deployment uses Python 3.7 by default, which pyRiemann doesn't support. But you can use a different Python version by adding an environment.yml to the repository.

Happy to open a PR to get this up and running!

**Comment by agramfort** [comment]
Excellent ! yes PR welcome. Thanks

**Comment by edublancas** [comment]
Hi! We have already onboarded a few open-source projects and have no capacity left. If we open new slots, I’ll open the PR! (closing this now)
