### ISSUE TITLE
Visualization of the Riemann classification 

### ISSUE THREAD

**Issue by charlespan110** [pyRiemann/pyRiemann#314]
Dear,

Thank you so much for your contribution to the field of BCI! The package and API are really easy to use and yield a nice performance.
I find a paper authored by your developer that extract patterns from EEG/EMG signals with Riemann methods, here is the reference:
[1] A. Barachant, J. B. Carmel, K. M. Friel, and D. Gupta, “Extraction of motor patterns from joint EEG/EMG recording: A Riemannian Geometry approach.”.
I would like to quest whether it is possible to visualize the Riemann based classification result, just resemble to the Common Spatial Patterns with topography with the Riemann package?

Best,
Charlie

**Comment by agramfort** [comment]
see https://arxiv.org/pdf/2107.14398

**Comment by charlespan110** [comment]
> see https://arxiv.org/pdf/2107.14398
> […](#)
> Message ID: ***@***.***>


Thank you for your response!

**Comment by qbarthelemy** [comment]
@charlespan110, don't hesitate to open a pull-request to add this visu to the package!
