### ISSUE TITLE
Fix: Tutorials link on site

### ISSUE THREAD

**Issue by andrewjaykeller** [pyRiemann/pyRiemann#32]
See Dead link: http://pythonhosted.org/pyriemann/auto_tutorials/index.html

**Comment by qbarthelemy** [comment]
Tutorial link has been removed with this commit:
https://github.com/pyRiemann/pyRiemann/commit/9ff48f0e4b9b090034f53105a45fc75cf69a6cef#diff-3161f66a61b9ed68303607f1dbdce1c7bdcc69c42f8ea1c2051a07a579ebcf5dL88
