### ISSUE TITLE
Tracking: Tutorials

### ISSUE THREAD

**Issue by andrewjaykeller** [pyRiemann/pyRiemann#33]
An issue to track the creation and testing of tutorials.

**Comment by alexandrebarachant** [comment]
Thank AJ,

What kind of tutorial would you like, i'm planning to do at least 2 : 
- [ ] Motor imagery classification
- [ ] Evoked potential classification

it might worth it do to a small one about spatial filtering as a way to reduce dimension. 

@kingjr : any other idea ?

**Comment by pushtheworldllc** [comment]
If you can provide those that would be great!

**Comment by kingjr** [comment]
What is the question exactly?

**Comment by alexandrebarachant** [comment]
i should create some tutorial to help people getting started. beside the two obvious tutorial on how to use pyRiemann for motor imagery and ERP classification, do you have any other idea/request.

It could be a way to explain and devellop non trivial questions or tackle some common problems. I think one about dimensionality reduction and regularization of covariance matrices is appropriate.

**Comment by kingjr** [comment]
yes, I would explain the cov regularization, that seems like a common blocker

**Comment by kingjr** [comment]
maybe another for the new objects you recently implemented?

**Comment by pushtheworldllc** [comment]
Potato!
* Building your first potato* Offline use of a potato for post processing* Online use for real time artifact rejection  

AJ Keller
Founder 
Push The World
843-471-0039




On Thu, Jul 28, 2016 at 9:28 PM -0400, "Jean-Rémi KING" <notifications@github.com> wrote:












maybe another for the new objects you recently implemented?

**Comment by qbarthelemy** [comment]
Regarding all examples added in the gallery since v0.2.7, I think this issue could be closed.
