### ISSUE TITLE
 Log map log-euclidean metric

### ISSUE THREAD

**Issue by antoinecollas** [pyRiemann/pyRiemann#334]
I was reading the log map associated with the different metrics, and I was surprised by the one of the log Euclidean metric.
Indeed, I doubt the log map of the log-Euclidean metric is this simple:

https://github.com/pyRiemann/pyRiemann/blob/f14f3b81888b912217bdb4abf0ecdf959672b9e4/pyriemann/utils/tangentspace.py#L273

For example, in eq. (2) of http://proceedings.mlr.press/v37/huanga15.pdf , the log map involves the computation of the differential of the matrix exponential.

Did I miss something?

**Comment by qbarthelemy** [comment]
You are absolutely right. The problem is being solved with #332.

**Comment by qbarthelemy** [comment]
Solved with merge of #332
