### ISSUE TITLE
[EHN] [Easy] Choose AJD algorithm for multi-class CSP

### ISSUE THREAD

**Issue by alexandrebarachant** [pyRiemann/pyRiemann#49]
Ajd algorithm for multiclass CSP is ajd_pham, which can be slow for high dimension. 3 different ajd algorithm are currently implemented (here : https://github.com/alexandrebarachant/pyRiemann/blob/master/pyriemann/utils/ajd.py). 

We just need to add a new argument, and make a switch here : 
https://github.com/alexandrebarachant/pyRiemann/blob/master/pyriemann/spatialfilters.py#L333

An example with a benchmark would be great

**Comment by qbarthelemy** [comment]
Benchmark of ajd methods has been added with
https://github.com/benchopt/benchmark_jointdiag/pull/9

Issue is closed.
