### ISSUE TITLE
[ENH] Add example with benchark of different mean/distance metric for MDM

### ISSUE THREAD

**Issue by alexandrebarachant** [pyRiemann/pyRiemann#52]
MDM works by default with Riemannian mean and distance, but different combination of metrics can be set

```python
metric = dict(distance='euclid', mean='wasserstein')
mdm = MDM(metric=metric)
```

The choice of metric impact peformance and computational cost. An example with benchmark of different metric for the mean and distance needed.

**Comment by qbarthelemy** [comment]
Accuracies and computational times are compared for the three main metrics (`riemann`, `logeuclid` and `euclid`), since #182.
