### ISSUE TITLE
Kernel Matrix Representation

### ISSUE THREAD

**Issue by alexandrebarachant** [pyRiemann/pyRiemann#58]
From this [paper](http://www.cv-foundation.org/openaccess/content_iccv_2015/papers/Wang_Beyond_Covariance_Feature_ICCV_2015_paper.pdf) 
> Wang, Lei, et al. "Beyond covariance: Feature representation with nonlinear kernel matrices." Proceedings of the IEEE International Conference on Computer Vision. 2015.

we can replace covariance by a kernel matrix. In our case, we could apply a kernel function between any pair of channels to build the kernel matrix.

This could be an interesting functionality to implement. We could rely on scikit-learn [kernel functions](http://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise.kernel_metrics.html#sklearn.metrics.pairwise.kernel_metrics)

This could be done as a stand-alone Transformer (i.e. `KernelMatrixRepresentation`) or by extending the parameter `estimator` of the covariance estimation.

The later solution is easier, just extending the dict in `_check_est` from `utils.covariance` with what the `sklearn.metrics.pairwise.kernel_metrics` returns. However, we must add a mechanism to pass parameters to the estimator (which is not possible currently)

This is an easy one. Any Help is welcome

**Comment by plcrodrigues** [comment]
I personally prefer the second option, since passing parameters to the covariance estimator could be useful for doing other stuff in the future. What you think about including a dict `params` to the `__init__` function of the Covariances estimator? I guess it won't break the code, right?

**Comment by alexandrebarachant** [comment]
Yes, we should add a param, like `estimator_param` which would be a dict that can be passed to the estimator.
This would be usefull for existing estimator as well. 
and it would be better than what i currently do (pasing a `lambda x: est(x, param)`  to the estimator)

**Comment by plcrodrigues** [comment]
Cool. I would like to work on this! I've just read the paper and the idea seems indeed interesting.

**Comment by alexandrebarachant** [comment]
It would be great if you can do it !

I already tried very quickly with the moab (by passing a function to the estimator), depending on the kernel it actually improve performances marginally.

This is an easy PR. It would be great to also add an example with performances of various estimation methods.
