### ISSUE TITLE
Potato issue: Type Error!

### ISSUE THREAD

**Issue by andrewjaykeller** [pyRiemann/pyRiemann#66]
I'm getting a strange issue with potato!

```
TypeError: 'numpy.float64' object does not support item assignment
```

![image](https://user-images.githubusercontent.com/11437469/39998979-b5c3b59e-5755-11e8-8e7a-d90e09e89013.png)

Any ideas?

**Comment by vinay-jayaram** [comment]
What was the size of X? It may be that you just forgot to add a dummy dimension for trials?
