### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by Irving-ren** [pyRiemann/pyRiemann#69]
Hi, I just got in touch with pyRiemann. In the beginning, I wanna thanks for your work about pyRiemann based on the riemannian geometry.  Recently, this problem was occurred  when trying to use it.
![screenshot from 2018-09-03 16-32-40](https://user-images.githubusercontent.com/13758812/44973294-0397c280-af97-11e8-81c6-3d2fa3885269.png)
the related code as follows：

       # estimate covariances matrices
      cov = pyriemann.estimation(estimator='lwf').Covariances().fit_transform(data1)
      # cross validation
      mdm = pyriemann.classification.MDM()

     accuracy = cross_val_score(mdm, cov, y_vals_new)

     print(accuracy.mean())
I was adding  “(estimator='lwf')" after this error was popped up.

          ValueError: Covariance matrices must be positive definite.
Do you have any clue about this issue? Thank you.
Best 
Irving

**Comment by alexandrebarachant** [comment]
`estimation` is a module, so he can't be used like this. 
the correct thing would be :

 `cov = pyriemann.estimation.Covariances(estimator='lwf').fit_transform(data1)`

**Comment by terminator9487** [comment]
Hi, Alex.
I still had a confusion about pyRiemann. Are you familiar with the DEAP dataset？ My work is related with emotion classification using this dataset. Recently, I have done the classification job with pyRiemann without any pre-processing（feature extracting,selection). After compared with the former result(using HOC as feature extracting method）, I got confused.  According to the characteristics of EEG signal, the result that was directly using multi-class CSP with pyRiemann should be better than the former. However, the result didn't show that. Do you have any comments for this problem？ Thanks for your kindness.
Best
Irving

**Comment by terminator9487** [comment]
Hi, Alex.
 Sorry about bothering you again. Could you please tell me what's the accuracy when you use the pyRiemann for classification task? And, which data set did you use？ Thanks for your patience

Best 
Irving

**Comment by sylvchev** [comment]
Do you hear about [MOABB](https://github.com/NeuroTechX/moabb)? It should provide exactly this kind of information.
Do you have other questions or could we close the issue?
