### ISSUE TITLE
cannot import name 'Softmax' keras.layers

### ISSUE THREAD

**Issue by GagandeepDulku** [pyRiemann/pyRiemann#86]
Hi,

I am trying to use mtcnn library

`from mtcnn.mtcnn import MTCNN`

I have upgraded my scikit-learn library to '0.23.2', but the error is still there, can someone help ?

I am getting this issue

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c2876f7b1ea4> in <module>()
----> 1 from mtcnn.mtcnn import MTCNN

~\Anaconda3\lib\site-packages\mtcnn\__init__.py in <module>()
     24 # SOFTWARE.
     25 
---> 26 from mtcnn.mtcnn import MTCNN
     27 
     28 

~\Anaconda3\lib\site-packages\mtcnn\mtcnn.py in <module>()
     35 
     36 from mtcnn.exceptions.invalid_image import InvalidImage
---> 37 from mtcnn.network.factory import NetworkFactory
     38 
     39 

~\Anaconda3\lib\site-packages\mtcnn\network\factory.py in <module>()
     24 # SOFTWARE.
     25 
---> 26 from keras.layers import Input, Dense, Conv2D, MaxPooling2D, PReLU, Flatten, Softmax
     27 from keras.models import Model
     28 

ImportError: cannot import name 'Softmax'

**Comment by sylvchev** [comment]
You may contact [MTCNN](https://github.com/ipazc/mtcnn) to solve this issue.
@alexandrebarachant Could you close this one?
