### ISSUE TITLE
Suggestion: Move repo to NeuroTechX org, or add more maintainers

### ISSUE THREAD

**Issue by ErikBjare** [pyRiemann/pyRiemann#94]
I notice things are kinda stale here on the maintenance side. Notably, there are a few open PRs that look ready to merge (or at least there hasn't been any indication to the contrary).

I understand/assume that @alexandrebarachant is rather busy and only sporadically active in this repo, and I wouldn't ask him to be a more active maintainer (his time is probably better spent on other things than maintenance) so I'd like to suggest two possible solutions:

 1. Move the repo to the NeuroTechX org, where there's a community that could actively and happily support it.
 2. Add more maintainers to this repo.
    - From looking at the contributor stats, it looks like there aren't really any clear candidates. But @sylvchev has several open PRs and seems to have a good understanding of the subject matter.

The reason for asking this is that there are more issues here I'd like to open PRs to fix, but I won't put in the effort if I'm unlikely to get a response/merge anytime soon. An example would be to move from Travis (which has recently dropped their free-forever CI for open source) to GitHub Actions (see my changes in https://github.com/NeuroTechX/eeg-notebooks/pull/24 for an example).

There are probably more issues at hand, like how to deal with the PyPI upload rights, but I'd just like to throw these two options out and see what people think about these options.

**Comment by agramfort** [comment]
FYI I tried to reach out to @alexandrebarachant
<https://github.com/alexandrebarachant> in 3 different ways and no response.

I would also suggest to move the repo to another org. It could be:

http://github.com/pyRiemann/pyRiemann

to be more neutral but honestly both works for me

**Comment by Horschig** [comment]
To be honest, someone should just do it. Alexandre moved from academia to the industry some years ago, so probably there is little time for him to continue workong on this project.

**Comment by Horschig** [comment]
Although, this commit is pretty recent: https://github.com/alexandrebarachant/pyRiemann/commit/e232f016578fab0114a5d1de05311646f4a58e78

Anyway, anyone can just fork it and maintain your own version, right? So then having more collaborators in that version would be a way to go.

**Comment by agramfort** [comment]
ok I created the org https://github.com/pyRiemann

@alexandrebarachant can I ask you to transfer pyRiemann to this org
so we can more easily distribute the maintenance and make this great
software progress?

let me know if you would like to be an admin of this org

thanks !

>

**Comment by ErikBjare** [comment]
Personally, I think it makes more sense to move it into the @NeuroTechX org (since they've already taken several of @alexandrebarachant's past projects under their wing), but either works.

**Comment by agramfort** [comment]
no strong feelings. Maybe @alexandrebarachant can say what he wants?

>

**Comment by alexandrebarachant** [comment]
Hey all,

I think it's best if I transfer the repo to the pyRiemann org. I will do it ASAP. I need to figure out how to transfer pypi and the documentation hosting as well. 

@agramfort thanks a lot for taking the initiative here.

I'm glad to see there is an interest in continuing to improve this library. I don't use it very often anymore, and the simple truth is that I don't have the mental bandwidth to keep maintaining it. Things to fix (CI, docs, PR to merge) have piled up and it's just a bit too much for me at the moment. So I really welcome the initiative and I will gladly spend some time helping setting up the things so that we can get a fresh start here.

**Comment by agramfort** [comment]
thanks Alex !

we'll interate on the org repo

can you give us admin rights on pypi ? I am agramfort on pypi

**Comment by alexandrebarachant** [comment]
> can you give us admin rights on pypi ?

done

**Comment by agramfort** [comment]
my login on readthedocs is agramfort

**Comment by alexandrebarachant** [comment]
@agramfort I just added you as a maintainer. I don't have a strong opinion about using this versus gh-pages. At the time of the setup, this was a low effort solution, but if you are familiar with gh-pages, might be worth switching. the pyriemann doc use sphynx so it shouldnt be too hard.

**Comment by agramfort** [comment]
thanks !

let's try to stay with readthedocs for now

>
