### ISSUE TITLE
"the leading minor of order 60 of 'b' is not positive definite"

### ISSUE THREAD

**Issue by moonj94** [pyRiemann/pyRiemann#95]
I am trying to use the PyRiemann package to classify my data: 100 trials, 64 channels, 128 samples. I did not run common average referencing prior to running the following code:

This is the code I am applying:
`clf = make_pipeline(XdawnCovariances(n_components),
                        TangentSpace(metric='riemann'),
                        LogisticRegression())
    
    preds_rg     = np.zeros(len(Y_test))
    
    # reshape back to (trials, channels, samples)
    X_train      = X_train.reshape(X_train.shape[0], chans, samples)
    X_test       = X_test.reshape(X_test.shape[0], chans, samples)
    
    # train a classifier with xDAWN spatial filtering + Riemannian Geometry (RG)
    # labels need to be back in single-column format
    
    clf.fit(X_train, Y_train.argmax(axis = -1))`

and I am getting the following error:
`the leading minor of order 60 of 'b' is not positive definite. The factorization of 'b' could not be completed and no eigenvalues or eigenvectors were computed.`

Can you help me troubleshoot this?

**Comment by wbchao1997** [comment]
meeting the same error

**Comment by gabelstein** [comment]
Probably due to the covariance matrix not being positive definite (as it says in the error) since the covariance estimator defaults to 'scm'. 
Try XdawnCovariances(n_components, estimator='oas'), this guarantees positive definite covariance matrices.

**Comment by purvisampat** [comment]
Hey @gabelstein, I tried the estimator. It doesn't seem to solve the problem.

**Comment by qbarthelemy** [comment]
Covariance matrices must be shrunk in the original space, high-dimensional and thus probably badly conditioned, not in the reduced space. So, you should try `xdawn_estimator=oas` instead.

**Comment by purvisampat** [comment]
@qbarthelemy Thanks for the prompt solution! It worked for me.

**Comment by sylvchev** [comment]
Ok, we could close this issue!
