### ISSUE TITLE
Differences between covariance estimators, (scm,lwf,oas)?

### ISSUE THREAD

**Issue by moonj94** [pyRiemann/pyRiemann#97]
I'm wondering what the differences are between the three covariance estimators. I like that lwf and oas are regularized, but I am unsure how they are all different from each other. Also, what do the acronyms stand for?

**Comment by m9h** [comment]
Hi @moonj94, 
I think you will find this description useful from Scikit-Learn 
https://scikit-learn.org/stable/modules/covariance.html#shrunk-covariance
with an example
https://scikit-learn.org/stable/auto_examples/covariance/plot_covariance_estimation.html#sphx-glr-auto-examples-covariance-plot-covariance-estimation-py
HTH

**Comment by qbarthelemy** [comment]
Solved with #113.
