### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by Alina-Samokhina** [pyRiemann/pyRiemann#98]
It seems that this project fails to work with the latest sklearn version, even though there's a PR with a fix. 
Issues stay unanswered and PRs aren't merging. And there are good ones.

I know, it's kind of a duplicate of the Issue #94, but maybe one more issue could help.
It'd be great to hear something from the author @alexandrebarachant on this matter.

**Comment by ErikBjare** [comment]
#94 has been resolved. This can be closed.
